function [EnvironmentConditions, ...
            LogEnvironment, ...
            EnvironmentStatesDerivatives] ...
            = environment(EnvironmentConditions, ...
                            LogEnvironment, ...
                            EnvironmentStatesDerivatives, ...
                            PlantOutputs, ...
                            simulation_time__s, ...
                            EnvironmentStates, ...
                            ParametersEnvironment)

%% Extract Inputs
position_BI_I__m = PlantOutputs.RigidBody.position_BI_I__m;

%% Time
% Call model
current_time__mjd = ModifiedJulianDate.execute(simulation_time__s, ...
                                                ParametersEnvironment.ModifiedJulianDate);
% Set output
EnvironmentConditions.Time.current_time__mjd = current_time__mjd;

%% Earth Rotation
% Call model
earth_quaternion_EI = RotationEciToEcef.execute(current_time__mjd);

% Set output
EnvironmentConditions.EarthRotation.earth_quaternion_EI ...
                                         = earth_quaternion_EI;

%% Atmosphere
% Call model
[mass_density__kg_per_m3,  number_density__1_per_m3, temperature__K] ...
            = Nrlmsise00.execute(position_BI_I__m, ...
                                    earth_quaternion_EI, ...
                                    current_time__mjd, ...
                                    ParametersEnvironment.Nrlmsise00);

% Set output
EnvironmentConditions.EarthAtmosphere.temperature__K = temperature__K;
EnvironmentConditions.EarthAtmosphere.mass_density__kg_per_m3 = mass_density__kg_per_m3;
EnvironmentConditions.EarthAtmosphere.number_density__1_per_m3 = number_density__1_per_m3;

%% Gravitational Field
% Call model
gravitational_acceleration_I__m_per_s2 ...
    = SphericalHarmonicsGeopotential.execute(position_BI_I__m, ...
                                                earth_quaternion_EI, ...
                                                ParametersEnvironment. ...
                                                SphericalHarmonicsGeopotential);

% Set output
EnvironmentConditions.EarthGravitationalField.gravitational_acceleration_I__m_per_s2 ...
    = gravitational_acceleration_I__m_per_s2;

%% Magnetic Field
% Call model
magnetic_field_I__T = Igrf.execute(position_BI_I__m, ...
                                    earth_quaternion_EI, ...
                                    current_time__mjd, ...
                                    ParametersEnvironment.Igrf);
% Set output
EnvironmentConditions.EarthMagneticField.magnetic_field_I__T = magnetic_field_I__T;

%% States Derivatives
% no states -> EnvironmentStatesDerivatives can stay unaltered

%% Log relevant data
LogEnvironment.EnvironmentConditions = EnvironmentConditions;
LogEnvironment.EnvironmentStatesDerivatives = EnvironmentStatesDerivatives;
LogEnvironment.EnvironmentStates = EnvironmentStates;

end
