function [ActuatorsOutputs,...
            LogActuators, ...
            ActuatorsStatesUpdateInput] ...
            = actuators(ActuatorsOutputs, ...
                        LogActuators, ...
                        ActuatorsStatesUpdateInput, ...
                        EnvironmentConditions, ...
                        PlantOutputs, ...
                        ActuatorsCommands, ...
                        ActuatorsStates, ...
                        ParametersActuators)

end
