function [ActuatorsCommands, ...
            LogGncAlgorithms, ...
            GncAlgorithmsStatesUpdateInput] ...
            = gncAlgorithms(ActuatorsCommands, ...
                            LogGncAlgorithms, ...
                            GncAlgorithmsStatesUpdateInput, ...
                            SensorsOutputs, ...
                            GncAlgorithmsStates, ...
                            ParametersGncAlgorithms)

end
