function [PlantOutputs, ...
            LogPlantOutput] ...
            = plantOutput(PlantOutputs, ...
                            LogPlantOutput, ...
                            PlantStates, ...
                            ParametersPlant)

%% Log relevant data