function [SensorsOutputs, ...
            LogSensors, ...
            SensorsStatesUpdateInput] ...
            = sensors(SensorsOutputs, ...
                        LogSensors, ...
                        SensorsStatesUpdateInput, ...
                        EnvironmentConditions, ...
                        PlantOutputs, ...
                        PlantFeedthrough, ...
                        SensorsStates, ...
                        ParametersSensors)


end
