classdef Shuttlecock < SimulationConfiguration

    methods (Static)

        Parameters = configureParameters(obj)

        BusesInfo = configureBuses(Parameters)

        [EnvironmentConditions, ...
            LogEnvironment, ...
            EnvironmentStatesDerivatives] ...
            = environment(EnvironmentConditions, ...
                            LogEnvironment, ...
                            EnvironmentStatesDerivatives, ...
                            PlantOutputs, ...
                            simulation_time__s, ...
                            EnvironmentStates, ...
                            ParametersEnvironment)
        
        [SensorsOutputs, ...
            LogSensors, ...
            StatesUpdateInput] ...
            = sensors(SensorsOutputs, ...
                        LogSensors, ...
                        EnvironmentConditions, ...
                        PlantOutputs, ...
                        PlantFeedthrough, ...
                        SensorsStates, ...
                        ParametersSatellite)

        [ActuatorsOutputs,...
            LogActuators, ...
            StatesUpdateInput] ...
            = actuators(ActuatorsOutputs, ...
                        LogActuators, ...
                        EnvironmentConditions, ...
                        DynamicsOutputs, ...
                        ActuatorsCommands, ...
                        ActuatorsStates, ...
                        ParametersSatellite)
                                
        [PlantFeedthrough, ...
            LogPlantDynamics, ...    
            PlantStatesDerivatives] ...
            = plantDynamics(PlantFeedthrough, ...
                                LogPlantDynamics, ...
                                EnvironmentConditions, ...
                                ActuatorsOutputs, ...
                                PlantStates, ...
                                ParametersSatellite)

        [PlantOutputs, ...
            LogPlantOutput] ...
            = plantOutput(PlantOutputs, ...
                            LogPlantOutput, ...
                            PlantStates, ...
                            ParametersSatellite)

        [ActuatorsCommands, ...
            LogGncAlgorithms, ...
            StatesUpdateInput] ...
            = gncAlgorithms(ActuatorsCommands, ...
                            LogGncAlgorithms, ...
                            SensorsOutputs, ...
                            GncAlgorithmsStates, ...
                            ParametersGncAlgorithms)

        [udp_data_vector, LogSendSimData] ...
            = sendSimData(LogSendSimData, ...
                            simulation_time__s, ...
                            LogEnvironment, ...
                            LogSensors, ...
                            LogActuators, ...
                            LogPlantDynamics, ...
                            LogPlantOutput,...
                            LogGncAlgorithms, ...
                            Parameters)

        [stop_criterion, LogStopCriterion] ...
            = stopCriterion(LogStopCriterion, ...
                            simulation_time__s, ...
                            LogEnvironment, ...
                            LogSensors, ...
                            LogActuators, ...
                            LogPlantDynamics, ...
                            LogPlantOutput,...
                            LogGncAlgorithms, ...
                            Parameters)

    end
end



